<Project Sdk="Microsoft.NET.Sdk">
	
	<Import Project="..\Common.props" />

	<ItemGroup>
		<!--<PackageReference Include="ClrHeapAllocationAnalyzer" Version="3.0.0" PrivateAssets="All" />-->
		<PackageReference Include="Open.Numeric.Primes" Version="4.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Open.Evaluation.Core\Open.Evaluation.Core.csproj" />
	</ItemGroup>

</Project>