<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\Common.props" />
	
	<ItemGroup>
	  <ProjectReference Include="..\Open.Evaluation.Arithmetic\Open.Evaluation.Arithmetic.csproj" />
	  <ProjectReference Include="..\Open.Evaluation.Boolean\Open.Evaluation.Boolean.csproj" />
	</ItemGroup>

</Project>